### ISSUE TITLE
ACTIVIDAD 8 ROADMAP Y KANBAN

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-jamm#2]
[RoadMap_Getion de Proyectos de Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-jamm/files/13208770/RoadMap_Getion.de.Proyectos.de.Software.pdf)

**Comment by NoeliaGlez** [comment]
30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
